//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstateAgancyEntities : DbContext
    {

        private static EstateAgancyEntities _context;

        public static EstateAgancyEntities GetContext()
        {
            if (_context == null)
            {
                _context = new EstateAgancyEntities();
            }
            return _context;
        }
        
        public EstateAgancyEntities()
            : base("name=EstateAgancyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agents> Agents { get; set; }
        public DbSet<Applications> Applications { get; set; }
        public DbSet<aStatus> aStatus { get; set; }
        public DbSet<aType> aType { get; set; }
        public DbSet<Authoriz> Authoriz { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Contracts> Contracts { get; set; }
        public DbSet<cStatus> cStatus { get; set; }
        public DbSet<cType> cType { get; set; }
        public DbSet<Deals> Deals { get; set; }
        public DbSet<Degree> Degree { get; set; }
        public DbSet<Diploma> Diploma { get; set; }
        public DbSet<dStatus> dStatus { get; set; }
        public DbSet<dType> dType { get; set; }
        public DbSet<EducPeriod> EducPeriod { get; set; }
        public DbSet<EstateObject> EstateObject { get; set; }
        public DbSet<eStatus> eStatus { get; set; }
        public DbSet<eType> eType { get; set; }
        public DbSet<Parameter> Parameter { get; set; }
        public DbSet<PersonalData> PersonalData { get; set; }
        public DbSet<PlaceOfStudy> PlaceOfStudy { get; set; }
        public DbSet<PriorityLevel> PriorityLevel { get; set; }
        public DbSet<Speciality> Speciality { get; set; }
        public DbSet<StudyForm> StudyForm { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TechnicalConclusion> TechnicalConclusion { get; set; }
        public DbSet<TechnicalCondition> TechnicalCondition { get; set; }
    }
}
