//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalData
    {
        public PersonalData()
        {
            this.Clients = new HashSet<Clients>();
            this.Diploma = new HashSet<Diploma>();
            this.Workers = new HashSet<Workers>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string pAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Diploma> Diploma { get; set; }
        public virtual ICollection<Workers> Workers { get; set; }
    }
}
